# AntiBuild (v1.0.1)
# Spigot link: https://www.spigotmc.org/resources/antibuild-1-7-x-1-16-x-customizable-per-world-opensource.87157/
# GitHub link: https://github.com/ProfliXx/AntiBuild
settings:
# Block break
# Disable block breaking by enabling this.
  block-break:
# Set custom permission to break blocks.
    permission: 'antibuild.bypass.break'
# If player doesn't have permission, this message will be sent.
    no-permission: '&c&l AntiBuild &8| &cYou are not allowed to break blocks in this world!'
# If this is enabled block breaking will be disabled.
    enabled: true
# World Section
# WHITELIST or BLACKLIST specific worlds, or just ALL of THEM
    worlds:
# If all is set to true worlds list down will be ignored
      all: false
# Select restriction mode (WHITELIST or BLACKLIST) Whitelist(Enabled Worlds) Blacklist(Disabled Worlds)
      mode: WHITELIST
# Worlds list (If only one world [ 'world' ] )
      list: [ 'world', 'world_nether', 'world_the_end' ]
#
# Block place
# Disable block placing by enabling this.
  block-place:
# Set custom permissions to place blocks.
    permission: 'antibuild.bypass.place'
# If player doesn't have permission, this message will be sent.
    no-permission: '&c&l AntiBuild &8| &cYou are not allowed to place blocks in this world!'
# If this is enabled block placing will be disabled.
    enabled: true
# World Section
# WHITELIST or BLACKLIST specific worlds, or just ALL of THEM
    worlds:
# If all is set to true worlds list down will be ignored
      all: false
# Select restriction mode (WHITELIST or BLACKLIST) Whitelist(Enabled Worlds) Blacklist(Disabled Worlds)
      mode: WHITELIST
# Worlds list (If only one world [ 'world' ] )
      list: [ 'world', 'world_nether', 'world_the_end' ]